#!/bin/bash

SCRIPTPATH=$(dirname $(realpath "$0"))

if [[ $1 == "h" ]] || [[ $1 == "help" ]]; then
	echo "moin meister"
elif [[ $1 == "add" && $2 == "chapter" ]] || [[ $1 == "create" && $2 == "chapter" ]]; then
	sh ${SCRIPTPATH}/create-chapter $3
elif [[ $1 == "ac" ]]; then
	sh ${SCRIPTPATH}/create-chapter $2
elif [[ $1 == "i" ]] || [[ $1 == "init" ]] || [[ $1 == "create" ]]; then
	sh ${SCRIPTPATH}/create-project $2
elif [[ $1 == "b" ]] || [[ $1 == "build" ]] || [[ $1 == "run" ]] || [[ $1 == "r" ]]; then
	sh ${SCRIPTPATH}/build-document $2
fi